name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}

    - name: Cache Android SDK/NDK
      uses: actions/cache@v3
      with:
        path: ~/.android
        key: android-sdk-${{ runner.os }}-${{ steps.get-date.outputs.date }}

    - name: Build with Buildozer
      uses: up9cloud/action-buildozer@master
      with:
        buildozer_version: master
        command: buildozer -v android debug
        repository_root: .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: bin/*.apk
